<?php

namespace Database\Seeders;

use App\Models\Rombel;
use Illuminate\Database\Seeder;

class RombelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "X TKR 1",
                "jurusan_id" => 2,
                "kelas_id" => 1,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "X TKR 2",
                "jurusan_id" => 2,
                "kelas_id" => 1,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "X TSM",
                "jurusan_id" => 3,
                "kelas_id" => 1,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "X TBKR",
                "jurusan_id" => 4,
                "kelas_id" => 1,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "X KI 1",
                "jurusan_id" => 1,
                "kelas_id" => 1,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "X KI 2",
                "jurusan_id" => 1,
                "kelas_id" => 1,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "X TKJ 1",
                "jurusan_id" => 5,
                "kelas_id" => 1,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "X TKJ 2",
                "jurusan_id" => 5,
                "kelas_id" => 1,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "X TKJ 3",
                "jurusan_id" => 5,
                "kelas_id" => 1,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "X RPL 1",
                "jurusan_id" => 6,
                "kelas_id" => 1,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "X RPL 2",
                "jurusan_id" => 6,
                "kelas_id" => 1,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "X RPL 3",
                "jurusan_id" => 6,
                "kelas_id" => 1,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XI TKRO 1",
                "jurusan_id" => 7,
                "kelas_id" => 2,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XI TKRO 2",
                "jurusan_id" => 7,
                "kelas_id" => 2,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XI TSM",
                "jurusan_id" => 3,
                "kelas_id" => 2,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XI TBKR",
                "jurusan_id" => 4,
                "kelas_id" => 2,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XI KI 1",
                "jurusan_id" => 1,
                "kelas_id" => 2,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XI KI 2",
                "jurusan_id" => 1,
                "kelas_id" => 2,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XI TKJ 1",
                "jurusan_id" => 5,
                "kelas_id" => 2,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XI TKJ 2",
                "jurusan_id" => 5,
                "kelas_id" => 2,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XI RPL 1",
                "jurusan_id" => 6,
                "kelas_id" => 2,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XI RPL 2",
                "jurusan_id" => 6,
                "kelas_id" => 2,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XII TKRO 1",
                "jurusan_id" => 7,
                "kelas_id" => 3,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XII TKRO 2",
                "jurusan_id" => 7,
                "kelas_id" => 3,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XII TBSM",
                "jurusan_id" => 8,
                "kelas_id" => 3,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XII TBO",
                "jurusan_id" => 9,
                "kelas_id" => 3,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XII KI 1",
                "jurusan_id" => 1,
                "kelas_id" => 3,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XII KI 2",
                "jurusan_id" => 1,
                "kelas_id" => 3,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XII TKJ 1",
                "jurusan_id" => 5,
                "kelas_id" => 3,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XII TKJ 2",
                "jurusan_id" => 5,
                "kelas_id" => 3,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XII TKJ 3",
                "jurusan_id" => 5,
                "kelas_id" => 3,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XII RPL 1",
                "jurusan_id" => 6,
                "kelas_id" => 3,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XII RPL 2",
                "jurusan_id" => 6,
                "kelas_id" => 3,
                "guru_id" => null,
                "siswa_id" => null,
            ],
            [
                "tapel_id" => 3,
                "semester_id" => 1,
                "name" => "XII RPL 3",
                "jurusan_id" => 6,
                "kelas_id" => 3,
                "guru_id" => null,
                "siswa_id" => null,
            ]
        ];
        Rombel::insert($data);
    }
}
